version: '3'
services:
  mysql:
    container_name: db2-lab4
    build:
      context: .
      dockerfile: Dockerfile.mysql
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - "mysql_data:/var/lib/mysql"
      - "mysql_scripts:/scripts"
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: db2-lab4-admin
    links:
      - "mysql:db"
    ports:
      - "8181:80"
volumes:
  mysql_data:
  mysql_scripts: