DROP TABLE IF EXISTS projects;

create table projects (
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50),
	description VARCHAR(53), -- Changed from 50 because of lengthy content below
	supervisor INT
);

insert into projects (name, description, supervisor) values ('Voltasillamma', 'Automated bi-directional capacity', 280);
insert into projects (name, description, supervisor) values ('Zathin', 'Cross-group demand-driven moratorium', 980);
insert into projects (name, description, supervisor) values ('Touaghjoyfax', 'Synergized eco-centric solution', 439);
insert into projects (name, description, supervisor) values ('Andalax', null, 691);
insert into projects (name, description, supervisor) values ('Treefalex', 'Quality-focused 3rd generation approach', 438);
insert into projects (name, description, supervisor) values ('Alapha', 'Down-sized static circuit', 729);
insert into projects (name, description, supervisor) values ('Voaya touch 2000', 'Fundamental contextually-based database', 558);
insert into projects (name, description, supervisor) values ('Fiex San', 'Configurable incremental framework', 210);
insert into projects (name, description, supervisor) values ('Fixe flex', 'Automated homogeneous hub', 791);
insert into projects (name, description, supervisor) values ('Spaen', 'Proactive attitude-oriented info-mediaries', 965);
insert into projects (name, description, supervisor) values ('Greenlame', 'Virtual even-keeled orchestration', 489);
insert into projects (name, description, supervisor) values ('Stringtoughio', 'Self-enabling solution-oriented data-warehouse', 244);
insert into projects (name, description, supervisor) values ('Konkluxio', 'Open-architected client-server data-warehouse', 291);
insert into projects (name, description, supervisor) values ('Tre somio', 'Intuitive systemic benchmark', 862);
insert into projects (name, description, supervisor) values ('Fintone 1', 'Implemented asymmetric functionalities', 950);
insert into projects (name, description, supervisor) values ('Vivaio', 'Implemented client-driven application', 260);
insert into projects (name, description, supervisor) values ('Voltsi llam', 'Profit-focused hybrid contingency', 910);
insert into projects (name, description, supervisor) values ('Lat lux', 'Mandatory maximized internet solution', 385);
insert into projects (name, description, supervisor) values ('Fintone 44', 'Vision-oriented non-volatile leverage', 411);
insert into projects (name, description, supervisor) values ('Volt sill am', 'Visionary bottom-line encryption', 707);
insert into projects (name, description, supervisor) values ('Fin-tone 22', 'Visionary exuding emulation', 531);
insert into projects (name, description, supervisor) values ('Flow-adesk', 'Digitized bandwidth-monitored leverage', 602);
insert into projects (name, description, supervisor) values ('Sonaaair', 'Reactive contextually-based monitoring', 886);
insert into projects (name, description, supervisor) values ('Konk lux', 'Reduced foreground customer loyalty', 948);
insert into projects (name, description, supervisor) values ('Span 123', 'Persevering analyzing neural-net', 526);
insert into projects (name, description, supervisor) values ('Subin222', 'Organic national analyzer', 775);
insert into projects (name, description, supervisor) values ('Transc of', 'Cross-platform executive neural-net', 727);
insert into projects (name, description, supervisor) values ('Lot lux', 'Persistent full-range complexity', 625);
insert into projects (name, description, supervisor) values ('Tres-Zap 11', 'Programmable multimedia archive', 432);
insert into projects (name, description, supervisor) values ('Lotstring LL', 'Business-focused tangible emulation', 457);
insert into projects (name, description, supervisor) values ('Cardguard IO', 'Balanced bandwidth-monitored attitude', 521);
insert into projects (name, description, supervisor) values ('Fix San IO', 'Expanded grid-enabled emulation', 724);
insert into projects (name, description, supervisor) values ('Alphazap IO', 'Switchable context-sensitive secured line', 578);
insert into projects (name, description, supervisor) values ('Holdlamis AA', 'Diverse regional attitude', 638);
insert into projects (name, description, supervisor) values ('Cardguard AA', 'Phased foreground portal', 842);
insert into projects (name, description, supervisor) values ('Asoka BB', 'Customizable client-driven capability', 921);
insert into projects (name, description, supervisor) values ('Fixflex BB', 'Versatile stable pricing structure', 714);
insert into projects (name, description, supervisor) values ('Viva B', 'Intuitive logistical intranet', 362);
insert into projects (name, description, supervisor) values ('Andalax C', 'Business-focused user-facing synergy', 898);
insert into projects (name, description, supervisor) values ('Tresom 2222', 'Monitored zero tolerance Graphical User Interface', 967);
insert into projects (name, description, supervisor) values ('Y-find C', 'Enterprise-wide maximized collaboration', 276);
insert into projects (name, description, supervisor) values ('Prodder C', 'Customer-focused encompassing initiative', 201);
insert into projects (name, description, supervisor) values ('Viva C', 'Profound holistic policy', 342);
insert into projects (name, description, supervisor) values ('Subin C', 'Object-based heuristic portal', 627);
insert into projects (name, description, supervisor) values ('Vo ya touch', 'Ameliorated didactic project', 671);
insert into projects (name, description, supervisor) values ('Home Ing D', 'Reverse-engineered mission-critical Graphic Interface', 710);
insert into projects (name, description, supervisor) values ('Wrapsafe D', 'Profit-focused national parallelism', 942);
insert into projects (name, description, supervisor) values ('Sonair1', 'Organized methodical access', 863);
insert into projects (name, description, supervisor) values ('Ranker1', 'Enhanced 24 hour Graphical User Interface', 841);
insert into projects (name, description, supervisor) values ('Aerified1', 'Business-focused zero defect website', 202);
insert into projects (name, description, supervisor) values ('Hatity2', 'Automated optimizing superstructure', 780);
insert into projects (name, description, supervisor) values ('Voltslam2', 'Team-oriented user-facing policy', 770);
insert into projects (name, description, supervisor) values ('Regrant2', 'Virtual responsive strategy', 261);
insert into projects (name, description, supervisor) values ('Overhold3', 'Intuitive analyzing infrastructure', 900);
insert into projects (name, description, supervisor) values ('Bigtax 2', 'Expanded needs-based knowledge base', 939);
insert into projects (name, description, supervisor) values ('Greenlam3', 'Ameliorated leading edge internet solution', 582);
insert into projects (name, description, supervisor) values ('Tresom4', 'Customer-focused user-facing software', 854);
insert into projects (name, description, supervisor) values ('Konk lux4', 'Inverse cohesive parallelism', 831);
insert into projects (name, description, supervisor) values ('Mat Lam Tam', 'Secured holistic frame', 901);
insert into projects (name, description, supervisor) values ('Tresom44', 'Compatible real-time solution', 959);
insert into projects (name, description, supervisor) values ('Temp55', 'Reduced eco-centric synergy', 379);
insert into projects (name, description, supervisor) values ('Solarbreeze53', 'Fully-configurable client-server extranet', 370);
insert into projects (name, description, supervisor) values ('Prodder321', 'Re-contextualized static project', 912);
insert into projects (name, description, supervisor) values ('Voya touch1', 'Persistent object-oriented support', 327);
insert into projects (name, description, supervisor) values ('Alphazapio1223', 'User-friendly impactful moratorium', 846);
insert into projects (name, description, supervisor) values ('Ran-kii', 'Horizontal high-level hardware', 479);
insert into projects (name, description, supervisor) values ('Fixflexii', 'Phased tangible algorithm', 599);
insert into projects (name, description, supervisor) values ('Flowdeskii', 'Public-key coherent functionalities', 750);
insert into projects (name, description, supervisor) values ('Bitwolfii', 'Polarised multi-state hardware', 787);
insert into projects (name, description, supervisor) values ('Fin toneii', 'Fundamental explicit model', 610);
insert into projects (name, description, supervisor) values ('Lotstringei', 'Down-sized optimal time-frame', 875);
insert into projects (name, description, supervisor) values ('Voyatouchei', 'Multi-channelled asymmetric superstructure', 752);
insert into projects (name, description, supervisor) values ('Asokae', 'Assimilated homogeneous software', 436);
insert into projects (name, description, supervisor) values ('Flowdesker', 'Streamlined foreground challenge', 813);
insert into projects (name, description, supervisor) values ('Hatityer', 'Object-based composite ability', 472);
insert into projects (name, description, supervisor) values ('Konklaber', 'Future-proofed logistical challenge', 302);
insert into projects (name, description, supervisor) values ('Ronstringer', 'Ergonomic maximized support', 439);
insert into projects (name, description, supervisor) values ('Alphazapper', 'Ergonomic modular Graphical User Interface', 829);
insert into projects (name, description, supervisor) values ('Tin 1', 'Inverse 4th generation application', 829);
insert into projects (name, description, supervisor) values ('Zaam-Dox BOO', 'Self-enabling exuding contingency', 414);
insert into projects (name, description, supervisor) values ('Konklab Foo', 'Upgradable encompassing neural-net', 878);
insert into projects (name, description, supervisor) values ('Kon klux Foo', 'Organic modular instruction set', 910);
insert into projects (name, description, supervisor) values ('TempsoftFoo', 'Innovative fault-tolerant attitude', 414);
insert into projects (name, description, supervisor) values ('AlphazapperFoo', null, 497);
insert into projects (name, description, supervisor) values ('TempFoo', null, 980);
insert into projects (name, description, supervisor) values ('Y-findZero', 'Decentralized bandwidth-monitored policy', 766);
insert into projects (name, description, supervisor) values ('WrapsafeZero', 'Centralized national process improvement', 696);
insert into projects (name, description, supervisor) values ('Y-SolowarmZero', 'Face to face explicit open architecture', 655);
insert into projects (name, description, supervisor) values ('R-ank', 'Automated dynamic alliance', 974);
insert into projects (name, description, supervisor) values ('DomainerZero', 'Synergistic 5th generation attitude', 529);
insert into projects (name, description, supervisor) values ('TrippledexZero', 'User-friendly bi-directional installation', 729);
insert into projects (name, description, supervisor) values ('TreeflexZero', 'Open-architected motivating hub', 955);
insert into projects (name, description, supervisor) values ('GreenlamOOO', 'Persevering discrete challenge', 853);
insert into projects (name, description, supervisor) values ('Cardify54', 'Persevering impactful system engine', 880);
insert into projects (name, description, supervisor) values ('Keylex32', 'Configurable exuding strategy', 689);
insert into projects (name, description, supervisor) values ('Aerified 2', 'Vision-oriented explicit support', 451);
insert into projects (name, description, supervisor) values ('Job124', 'Virtual asymmetric ability', 688);
insert into projects (name, description, supervisor) values ('Treeflex44', 'Operative client-server initiative', 927);
insert into projects (name, description, supervisor) values ('Double Up 2', 'Right-sized composite help-desk', 740);
insert into projects (name, description, supervisor) values ('Double Up 2', 'Devolved regional capability', 838);

